# Generated by Django 3.1.5 on 2021-02-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170221_0006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
